import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import type {SidebarItemCategoryConfig} from '@docusaurus/plugin-content-docs/lib/sidebars/types';

function autoCategory(
  dirName: string,
  label = dirName,
): SidebarItemCategoryConfig {
  return {
    type: 'category',
    label,
    items: [
      {
        type: 'autogenerated',
        dirName,
      },
    ],
  };
}

const sidebar: SidebarsConfig = {
  docs: [
    'about',
    {
      type: 'category',
      label: 'Weixin official account',
      collapsible: false,
      items: [
        autoCategory('Science'),
        autoCategory('Technology'),
        autoCategory('Humanities'),
        autoCategory('Stories', 'Short stories'),
      ],
    },
    {
      type: 'category',
      label: 'Zhihu',
      collapsible: false,
      items: [
        autoCategory('Digital', 'Digital circuit notes'),
        autoCategory('LaTeX'),
      ],
    },
  ],
};

export = sidebar;
