"use strict";
function autoCategory(dirName, label) {
    if (label === void 0) { label = dirName; }
    return {
        type: 'category',
        label: label,
        items: [
            {
                type: 'autogenerated',
                dirName: dirName
            },
        ]
    };
}
var sidebar = {
    docs: [
        'about',
        {
            type: 'category',
            label: 'Weixin official account',
            collapsible: false,
            items: [
                autoCategory('Science'),
                autoCategory('Technology'),
                autoCategory('Humanities'),
                autoCategory('Stories', 'Short stories'),
            ]
        },
        {
            type: 'category',
            label: 'Zhihu',
            collapsible: false,
            items: [
                autoCategory('Digital', 'Digital circuit notes'),
                autoCategory('LaTeX'),
            ]
        },
    ]
};
module.exports = sidebar;
